version: '3'
services:
  homebus-authacl-postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    networks: 
      - homebus-authacl-net
    env_file: .env.docker

  homebus-authacl-web:
    build: .
    command: ["bin/rails","server","-b","0.0.0.0","-p","3000"]
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - homebus-authacl-postgres
    volumes:
      - .:/app
    environment:
      DOCKER: docker
      RAILS_ENV: development
      RAILS_DOCKER: 1
    env_file: .env.docker
    networks: 
      - homebus-authacl-net 

networks:
  homebus-authacl-net:
